### ISSUE TITLE
You realize that all Youtube audio only goes up to 192kbps, right?

### ISSUE THREAD

**Issue by ayancey** [yask123/Instant-Music-Downloader#10]
This is cool, but upsampling is a sin.

**Comment by yask123** [comment]
Most of the time, I get a bitrate of 252 kbps, which is actually quite decent. http://i.imgur.com/Q3NEp1s.png (Instant Crush downloaded via this script)

**Comment by ayancey** [comment]
I don't think that's true...
http://www.h3xed.com/web-and-internet/youtube-audio-quality-bitrate-240p-360p-480p-720p-1080p
