### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by MrDini123** [yask123/Instant-Music-Downloader#106]
Hi!

I tried to install this nice tool to my nas, but when I try to download anything, it crashes with a long error flood...

Here You Can see the full output: https://asciinema.org/a/dxrdy8tdcqk9643g3mmaqpaam

Thanks!

**Comment by yask123** [comment]
Ah! Looks like there is a bug in `fixalbumart` module.
But I think it still downloaded the song? Can you check in your current directory is the song is downloaded there or not?

**Comment by MrDini123** [comment]
No, I Can't see the song in that directory...:(

But the youtube-dl is works if I manually download sy with it.

**Comment by yask123** [comment]
Ah! I see, this is a bug, and I have exams. I'll get time to fix this in first week of June.
Sorry for the inconvenience .
@jainaman224 Could you take a look at it (If you have time?)

**Comment by MrDini123** [comment]
Oh sorry! It seems like a youtube-dl issue. I used the youtube dl in the old python2.7, but a few days ago, I upgraded to the latest 3.5 python and after that, I reinstalled the youtube-dl using pip. I will open an issue at the youtube-dl's page.
