### ISSUE TITLE
Python3 breaks id3 tagging

### ISSUE THREAD

**Issue by Karunamon** [yask123/Instant-Music-Downloader#111]
Greetings,

When using a 3.x version of Python, id3 tags are unable to be inserted into downloaded files. An error:

```
Fixing id3 tags
a bytes-like object is required, not 'str'
```

..and the resulting file has no tags.

When using a 2.x version, I see a few extra lines of output:

```
WARNING: "id" field is not a string - forcing string conversion
-snip-
Fixing id3 tags
Invalid URL '': No schema supplied. Perhaps you meant http://?
```

but the resulting file is correct.

**Comment by yask123** [comment]
Why did you close this?

**Comment by Karunamon** [comment]
Figured out it was a problem with my environment. I'm a heavy user of pyenv, and switching environments solved the problem.
