### ISSUE TITLE
Why is this not pip installable?

### ISSUE THREAD

**Issue by IvanMalison** [yask123/Instant-Music-Downloader#12]

**Comment by yask123** [comment]
Its in Todo list, will be soon available as a packaged python script.

**Comment by yask123** [comment]
It is now.
Run `pip install instantmusic` to download it.

**Comment by KumarRishabh** [comment]
I cannot install using this command. The command line is showing many errors.

**Comment by yask123** [comment]
It works, can you paste the errors you got ?

**Comment by swapnil-ss** [comment]
i also got errors when i run $ pip install instantmusic but it worked fine with 
$ sudo pip install instantmusic
