### ISSUE TITLE
A couple of english issues in comments

### ISSUE THREAD

**Issue by aviaryan** [yask123/Instant-Music-Downloader#13]
https://github.com/yask123/Instant-Music-Downloader/blob/master/music_downloader.py#L10

We do not want to <s>except</s> accept empty inputs :)

https://github.com/yask123/Instant-Music-Downloader/blob/master/music_downloader.py#L24

May change when Youtube Website <s>may get</s> gets updated in the future.

**Comment by aviaryan** [comment]
I hope the except one was not done on purpose. :wink:

**Comment by yask123** [comment]
lol, that was embarrassing. Thanks :+1:
