### ISSUE TITLE
Not able to download in mp3 format

### ISSUE THREAD

**Issue by aviaryan** [yask123/Instant-Music-Downloader#19]
I have tried this script 7-8 times now and I have never been able to download music in .mp3 format.
It is either *.m4a or *.webm . 
Can something be done here ?

**Comment by gamegoofs2** [comment]
I get the same thing. Do you have the FFmpeg installed properly? I think that's the solution, however I didn't see where the python script was referencing it.

**Comment by yask123** [comment]
It would automatically convert to `.mp3` file, but only if you have ` ffmpeg or avconv`, installed.
On `OSX` you can run `brew install libav` to install it.
On Ubuntu `libav-tools` can be installed by running `sudo apt-get install libav-tools` 
Clearly, `installation script` requires more work: https://github.com/yask123/Instant-Music-Downloader/blob/master/install.sh#L8

**Comment by gamegoofs2** [comment]
What about a solution for Windows? I tried installing FFmpeg, but I still get webm and m4a files.

**Comment by yask123** [comment]
After installing `FFmpeg` did you put them in the current path ?
Or maybe put `ffmpeg../bin` in your environment path variable .
Refer this: http://stackoverflow.com/questions/14185867/extract-audio-with-youtube-dl-on-windows

**Comment by gamegoofs2** [comment]
That was the fix. The FFmpeg said it added it to the Path, but I guess it really didn't. Manually added and works flawlessly.

**Comment by marcfp** [comment]
With ubuntu focal and debian stable 10, i can't build the source using pip3 becouse system can't install beautifullsoup.
