### ISSUE TITLE
Are you sure that you have all the dependencies covered in requirements.txt?

### ISSUE THREAD

**Issue by so4pmaker** [yask123/Instant-Music-Downloader#3]
Have a look the following screen. 
![screen shot 2015-09-16 at 1 54 55 pm](https://cloud.githubusercontent.com/assets/2987763/9899906/94095e0a-5c7a-11e5-969e-4a5637a9eb58.png)

**Comment by whizzzkid** [comment]
Fixed in https://github.com/yask123/Instant-Music-Downloader/pull/5

**Comment by barronlroth** [comment]
Still getting this exact issue. Any idea why?

**Comment by yask123** [comment]
You need either `ffmpeg` or `avconv` to convert to `.mp3`.
On mac you can run `brew install ffmpeg` to install it. (if you have brew installed http://brew.sh )

**Comment by yask123** [comment]
Updated readme,
