### ISSUE TITLE
Mac OS X install issues

### ISSUE THREAD

**Issue by 5c0tt** [yask123/Instant-Music-Downloader#31]
Hello, On Mac OS X I could not get this installed until I searched and used an easy_install command, which then had a ton of errors, needing sudo.  It finally installed.  I am finding it is not terribly great at matching the type of music I am looking for, which is rather mainstream to be honest.

Current issue:
Once it does find a song, I select "y" and get the below error, which I am sure is installed in /Library as I can see it there.
sh: youtube-dl: command not found

Also, is there a help or man page, where do I configure where downloads go, what format they are in, specific perhaps minimum bitrates etc? Where are the songs sourced from ,are these all youtube rips?

**Comment by tedmiston** [comment]
If you install globally with pip, it should grab the youtube-dl dependency for you:

```
pip install instantmusic
```

You may want to install ffmpeg as well:

```
brew install ffmpeg
```

**Comment by xyclos** [comment]
I don't think OS X ships with pip. It might be a good idea to mention in the readme:

`sudo easy_install pip`

**Comment by yask123** [comment]
@5c0tt You can run `$ instantmusic -h` for help
```
❯ instantmusic -h                                                   
usage: instantmusic [-h] [-p] [-q] [-s SONG [SONG ...]]
                    [-l SONGLIST [SONGLIST ...]] [-f FILE [FILE ...]]

Instantly download any song!

optional arguments:
  -h, --help            show this help message and exit
  -p                    Turn off download prompts
  -q                    Run in quiet mode. Automatically turns off prompts.
  -s SONG [SONG ...]    Download a single song.
  -l SONGLIST [SONGLIST ...]
                        Download a list of songs, with lyrics separated by a
                        comma (e.g. "i tried so hard and got so far, blackbird
                        singing in the dead of night, hey shawty it's your
                        birthday).
  -f FILE [FILE ...]    Download a list of songs from a file input. Each line
                        in the file is considered one song.
```
@xyclos I added link to `pip` installation in `Readme`
