### ISSUE TITLE
Why only first search?

### ISSUE THREAD

**Issue by AshBardhan** [yask123/Instant-Music-Downloader#34]
Just asked for song via lyrics `listen to the bullshit he learned in school`
Go something like `Anita Sarkeesian bullshit taught in schools 11-12 grade` as a result. 
Even though the actual song was in the 4th place in that search.

There should be a way. where you can show the matches

**Comment by yask123** [comment]
This feature has been added recently.
https://github.com/yask123/Instant-Music-Downloader/blob/master/music_downloader.py
You can install it from the source if you wish to use it now, I haven't updated the package as yet.

**Comment by AshBardhan** [comment]
Any command for updating this application?

**Comment by yask123** [comment]
Just updated the package.
Run `sudo pip install instantpackage --upgrade` to upgrade to v 1.2

**Comment by AshBardhan** [comment]
Thanks mate
