### ISSUE TITLE
error when reading from stdin

### ISSUE THREAD

**Issue by skibz** [yask123/Instant-Music-Downloader#36]
```bash
antino:~ ant$ echo abc | instantmusic
Enter songname/ lyrics/ artist.. or whatever
> Making a Query Request!
Found: ABC SONG | ABC Songs for Children - 13 Alphabet Songs & 26 Videos
Download song (y/n)? Traceback (most recent call last):
  File "/usr/local/bin/instantmusic", line 37, in <module>
    prompt = raw_input("Download song (y/n)? ")
EOFError: EOF when reading a line
antino:~ ant$
```

the `Download song (y/n)` prompt immediately errors out when piping text to `instantmusic`

**Comment by yask123** [comment]
Fixed in b26c88d9f6cd636f8384265d025828be652a27fd.
Note, I haven't yet updated the python module, so this change won't get affected by running `pip install instantmusic --upgrade`.

You'll need to install it from source.
