### ISSUE TITLE
feature: command line options

### ISSUE THREAD

**Issue by skibz** [yask123/Instant-Music-Downloader#37]
a `-y` or `--yes` flag for accepting the `Download song (y/n)` prompt?
would make using this program in shell scripts easier :smile:

**Comment by mondayrain** [comment]
@sulami and I have put in pull requests with command line options included (see #24 and #41), so when @yask123 merges those changes you should be good to go!

**Comment by yask123** [comment]
Fixed in b26c88d9f6cd636f8384265d025828be652a27fd commit.
Thanks @mondayrain  for helping :smile:
