### ISSUE TITLE
Failed at audioconversion says unknown encoder 'libmp3lame'

### ISSUE THREAD

**Issue by iamads** [yask123/Instant-Music-Downloader#39]
On downloading song  I get the following warnings and error on Ubuntu 12.04 machine

WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
[avconv] Destination: New hd song (Suno na sange mar mar)-8gc4U6L2hZM.mp3
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
ERROR: audio conversion failed: Unknown encoder 'libmp3lame'

I tried updating libav-tools but it is already the newest version.

**Comment by yask123** [comment]
Strange, run `$ sudo apt-get update && sudo apt-get install libav-tools`

**Comment by iamads** [comment]
@yask123 youtube-dl required libavcodec-extra-53 for encoding to mp3.

http://askubuntu.com/questions/398731/an-error-with-youtube-dl
