### ISSUE TITLE
Feature Request : MultiSong support

### ISSUE THREAD

**Issue by vijayrawatsan** [yask123/Instant-Music-Downloader#43]
Resolved in https://github.com/yask123/Instant-Music-Downloader/pull/42
Show users atleast first page of search results like below screenshot:

<img width="910" alt="instantmusic" src="https://cloud.githubusercontent.com/assets/985228/10399326/a74573ca-6ecf-11e5-8d34-df0bfd17a27a.png">

**Comment by yask123** [comment]
Just updated the module which includes this feature.
Run `sudo pip install instantmusic --upgrade` to try.
