### ISSUE TITLE
/usr/local/bin/youtube-dl: Permission denied Sudo didnt work.

### ISSUE THREAD

**Issue by Airget** [yask123/Instant-Music-Downloader#46]
sudo didnt help

**Comment by yask123** [comment]
can you paste exact commands you typed in your terminal and its output here ?

**Comment by Airget** [comment]
Aarons-MacBook-Air:~ Aaron$ sudo instantmusic
Password:
Enter songname/ lyrics/ artist.. or whatever
> Cheerleader
Making a Query Request! 
Found: OMI - Cheerleader (Felix Jaehn Remix) [Official Video]
Download song (y/n)? y
Downloading...
sh: /usr/local/bin/youtube-dl: Permission denied
Aarons-MacBook-Air:~ Aaron$

**Comment by yask123** [comment]
Ah.. run `chmod a+x /usr/local/bin/youtube-dl` to fix it.

**Comment by Airget** [comment]
Thanks

**Comment by JohnCosnett** [comment]
on mac% `sudo chmod a+x /usr/local/bin/youtube-dl`

**Comment by jordaneOnizuka** [comment]
Thanks ccosnett

**Comment by Lucaslah** [comment]
> this worked on my mac% `sudo chmod a+x /usr/local/bin/youtube-dl`

This worked for me.

**Comment by iPoe** [comment]
The idea worked for me, but beacuse I used snap to install I needed to change the command:
sudo chmod a+x /snap/bin/youtube-dl

**Comment by manman-dong** [comment]
> 啊..跑去`chmod a+x /usr/local/bin/youtube-dl`修复它。

chmod: Unable to change file mode on /usr/local/bin/youtube-dl: Operation not permitted

**Comment by manman-dong** [comment]
> Ah.. run `chmod a+x /usr/local/bin/youtube-dl` to fix it.

chmod: Unable to change file mode on /usr/local/bin/youtube-dl: Operation not permitted
