### ISSUE TITLE
After latest update utilizing readline module, virtual machine no longer supports instantmusic

### ISSUE THREAD

**Issue by shaun10** [yask123/Instant-Music-Downloader#58]
![screen shot 2015-10-11 at 3 15 49 pm](https://cloud.githubusercontent.com/assets/7233643/10419383/fddc79c0-702a-11e5-9432-c95ae7b032e7.png)

Anyone know why readline import isn't working in virtualenv on OS X 10.11? Having permissions issues with install in regular system environment with writing to:

'/System/Library/Frameworks/Python.framework/Versions/2.7/etc'

Believe SH trying to write to locked areas of El Capitan.

**Comment by yask123** [comment]
This issue is not related to Instant Music Downloader.
Refer to this: http://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-el-capitan-max-os-x-upgrade

Quick fix is to install `pip` using `brew`:
`$ brew install python`
