### ISSUE TITLE
Add flags for various settings

### ISSUE THREAD

**Issue by whizzzkid** [yask123/Instant-Music-Downloader#6]
Adding flags for audio quality, download location, etc should be great.

**Comment by yask123** [comment]
Quality of any audio is really important.  We should probably just pass `-f best audio` to `youtube-d`l by default to always grab the best audio quality possible. 

Choosing a download location maybe an overplay for this script (Entering download location for every download is too much work).

I wished users would first go to the directory where they wanted to download music and then run this script to download all music in their `pwd`.
But for this, the user needs to add the folder which contains this script in his environment variable `PYTHONPATH`. This will enable users to run script from any directory.

We need to add something like `export PYTHONPATH="${PYTHONPATH}:/path/to/instant_music_downloader/"`  to our installer script.

**Comment by yask123** [comment]
Added `best audio` quality flag, fixed `super_installer.py` bug.
4e8f7e9b03298ba01c9a04fb31eba1642ea054ff
