### ISSUE TITLE
Tag data for songs

### ISSUE THREAD

**Issue by ssundarraj** [yask123/Instant-Music-Downloader#60]
Currently, downloaded songs don't have artist, album and other details. It would be a nice feature if these details could be added automatically.

**Comment by yask123** [comment]
Added this feature in commit 71145bc3e0cf2eba5e7b2aa3082cd38d13ae66ad 
Update sudo pip install instantmusic --upgrade to try.
See: https://github.com/yask123/Instant-Music-Downloader/blob/master/README.md#mp3-tags
