### ISSUE TITLE
"sh: youtube-dl: command not found" error on Mac

### ISSUE THREAD

**Issue by strix** [yask123/Instant-Music-Downloader#62]
After a fresh ```sudo pip install instantmusic``` on Mac, choosing a song would result in the following output:
```sh
Download "song-name"? (y/n) y
Downloading
sh: youtube-dl: command not found
Fixing id3 tags
Traceback (most recent call last):
  File "/usr/local/bin/instantmusic", line 196, in <module>
    main()
  File "/usr/local/bin/instantmusic", line 139, in main
    downloaded = query_and_download(search)
  File "/usr/local/bin/instantmusic", line 107, in query_and_download
    audiofile = eyed3.load((title+'.mp3'))
  File "/Library/Python/2.7/site-packages/eyed3/core.py", line 81, in load
    raise IOError("file not found: %s" % path)
IOError: file not found: song-name.mp3
```

The root of the problem was obviously youtube-dl.  I looked into it and for some reason pip downloaded the youtube-dl requirement but no executable in resulted from it (in ```/usr/local/bin/``` or anywhere else).  I'm not sure if this is just my configuration with pip (or something else entirely) or not but a simple
```sh
brew install youtube-dl
```
got things working for me.  If I'm not the only Mac user with this error, you might consider adding the above command under the Mac installation documentation.  If you know what my error is with youtube-dl not being available upon installing with pip, any tips on how to get it fixed would be appreciated.

**Comment by yask123** [comment]
Fixed here: https://github.com/yask123/Instant-Music-Downloader/commit/c641e64e6252742e9ea37e6ab3edb621e124a682 
 
Thanks for reporting the bug
