### ISSUE TITLE
Wrong indentation

### ISSUE THREAD

**Issue by bitwave** [yask123/Instant-Music-Downloader#68]
I got this error:

instantmusic 
  File "/usr/bin/instantmusic", line 131
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation

BTW: I'm using python3

**Comment by yask123** [comment]
err.. my bad. Fixing! Thanks for reporting,

**Comment by bitwave** [comment]
no problem ;)

**Comment by yask123** [comment]
Fixed 7be8812c8ab3104bf4d434eb7361f0bb44018d4d 
Run `pip install instantmusic --upgrade`
