### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by sagarghai** [yask123/Instant-Music-Downloader#78]
every time i try to download some song it gives me an error with the following details. can you help?

local variable 'audiofile' referenced before assignment
couldnt get album art

**Comment by yask123** [comment]
Thanks for reporting the issue. I'll look into it.

**Comment by sagarghai** [comment]
Have something to tell @yask123

**Comment by underscorejho** [comment]
I've got a similar error. Output:

```
Fixing id3 tags
a bytes-like object is required, not 'str'
couldnt get album art
Traceback (most recent call last):
  File "/usr/bin/instantmusic", line 286, in <module>
    main()
  File "/usr/bin/instantmusic", line 283, in main
    print('Downloaded: %s' % ', '.join(downloads))
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by yask123** [comment]
I'll be fixing it after a week, college exams :cry: 
Thanks for reporting

**Comment by sagarghai** [comment]
A possible resolve for the issue: try to export proxy and do it for http, https, tcp and udp. It works fine now on my system.

**Comment by Jambon1510** [comment]
issue still going on, any plan to fix this?

**Comment by yask123** [comment]
Not maintaining this anymore.
