### ISSUE TITLE
why use readline ?

### ISSUE THREAD

**Issue by aviaryan** [yask123/Instant-Music-Downloader#80]
[readline](https://pypi.python.org/pypi/readline) seems to work only on Mac OS X. This makes the script unusable, atleast on Windows.

**Comment by yask123** [comment]
Ah, I didn't know that. readlines enables you to move back typing cursor (Useful to edit if you made typo while entering song name and wish to edit it).
Could there be an alternative workaround for it to work in windows ?

**Comment by aviaryan** [comment]
Sorry but I don't get it. :disappointed:  To edit something you just wrote on the terminal, why not just delete everything or go back using left arrow key and change it.

**Comment by gummywormz** [comment]
Install pyreadline. It fixes the script on windows.

**Comment by aviaryan** [comment]
Thanks. That fixed the issue

**Comment by aviaryan** [comment]
Opened pull #82 to properly fix this issue.
