### ISSUE TITLE
-bash: /usr/local/bin/youtube-dl: Permission denied (youtube-dl)

### ISSUE THREAD

**Issue by Butterblume** [yask123/Instant-Music-Downloader#84]
Please help me,
I want to download a youtube video with its subtitles
but then this: -bash: /usr/local/bin/youtube-dl: Permission denied always appears.

v******:~ vivien$ youtube-dl --write-srt --wirte-auto-sub 'https://www.youtube.com/watch?v=4YhpWZCdiZc'
-bash: /usr/local/bin/youtube-dl: Permission denied

**Comment by yask123** [comment]
Did you try prepending  `sudo` to your command ?

**Comment by hut8** [comment]
What is the mode set to on /usr/local/bin/youtube-dl ? How did you install it? That usually means the `x` bit isn't set for you.

**Comment by Butterblume** [comment]
Hey thank you, it worked out in the end :)
