### ISSUE TITLE
youtube_dl-0.0.2/bin/youtube-dl:2: Invalid char `\x03' in expression (SyntaxError)

### ISSUE THREAD

**Issue by semaj** [yask123/Instant-Music-Downloader#85]
I get 
`youtube_dl-0.0.2/bin/youtube-dl:2: Invalid char `\x03' in expression (SyntaxError)`

when downloading, and nothing actually downloads. 

Btw - I love this thing!

**Comment by yask123** [comment]
What was the query ? 
Can you mention steps to reproduce this error?

**Comment by semaj** [comment]
Never mind! This was due to a conflict with an existing ruby gem called `youtube_dl`. I `gem uninstall youtube_dl`'d, and everything is good. Thanks man!
