### ISSUE TITLE
Case sensitivity ("Download song (y/n)")

### ISSUE THREAD

**Issue by ramimac** [yask123/Instant-Music-Downloader#87]
Responding with "Y" or "yes" causes application to quit with no feedback. Ideally the prompt should accept all reasonable inputs, or provide feedback upon quitting ("Please respond with "y" or "n")

**Comment by yask123** [comment]
Hey, Thanks for your suggestions. I agree, will fix this in a few days.

**Comment by iamshubh22** [comment]
@yask123 I would like to work on this.

**Comment by yask123** [comment]
@iamshubh22 Awesome! Send the PR with the issue name in the commit message after you are done.

**Comment by yask123** [comment]
@iamshubh22  If you need anyhelp, you can ping me anytime :) 
IRC: yask on irc.freenode.net — Twitter: @yask123

**Comment by iamshubh22** [comment]
@yask123 There were some issues with my laptop. I will do it by tomorrow.
